-- ============================================================================
-- AIIMS Bibinagar Hall Ticket System — PostgreSQL schema (Supabase)
--
-- HOW TO RUN THIS:
--   1. Open your project at https://supabase.com
--   2. Click "SQL Editor" in the left sidebar -> "New query"
--   3. Paste this entire file in and click "Run"
-- You only need to do this once, when first setting up the project.
--
-- Real tables — courses, subjects, applications, and the subjects each
-- application registered for — each with their own columns and
-- relationships, matching the Database Schema document.
-- ============================================================================

create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- courses — one row per course/programme (e.g. "I MBBS", "B.Sc Nursing I Year")
-- ----------------------------------------------------------------------------
create table if not exists courses (
  id text primary key,
  name text not null unique,
  code text not null,
  fee_tier text,                 -- null = flat (sum of subject fees), 'tier1' or 'tier2'
  exam_title text,               -- e.g. "B.Sc. Nursing Regular Final Professional Examination"
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- subjects — one row per subject offered within a course
-- ----------------------------------------------------------------------------
create table if not exists subjects (
  id text primary key,
  course_id text not null references courses(id) on delete cascade,
  name text not null,
  fee numeric not null default 0,
  exam_date date,
  exam_date_to date
);
create index if not exists subjects_course_id_idx on subjects(course_id);

-- ----------------------------------------------------------------------------
-- applications — one row per student examination application
-- ----------------------------------------------------------------------------
create table if not exists applications (
  id text primary key,                     -- e.g. "APP..." (generated by the app)
  hall_ticket_no text,                     -- Roll No., entered by the student
  status text not null default 'pending',  -- pending | approved | rejected
  name text not null,
  father text,
  dob date,
  mobile text,
  guardian_mobile text,
  perm_address text,
  comm_address text,
  photo_data_url text,                     -- photograph, base64-encoded
  signature_data_url text,                 -- signature image, base64-encoded (if uploaded)
  signature_mode text default 'upload',    -- 'upload' or 'digital' (Sd/-)
  course_id text references courses(id) on delete set null,
  course_name text,                        -- kept alongside course_id so history
                                            -- survives even if the course is later deleted
  total_fee numeric default 0,
  utr text,
  receipt_data_url text,
  receipt_name text,
  receipt_type text,
  receipt_size integer,
  remarks text default '',
  history jsonb not null default '[]'::jsonb,
  submitted_at timestamptz not null default now()
);
create index if not exists applications_course_id_idx on applications(course_id);
create index if not exists applications_mobile_idx on applications(mobile);
create index if not exists applications_hall_ticket_no_idx on applications(hall_ticket_no);

-- ----------------------------------------------------------------------------
-- application_subjects — which subjects each application registered for
-- ----------------------------------------------------------------------------
create table if not exists application_subjects (
  id uuid primary key default gen_random_uuid(),
  application_id text not null references applications(id) on delete cascade,
  subject_id text references subjects(id) on delete set null,
  subject_name text not null,   -- snapshot, in case the subject is later removed
  exam_date date,
  exam_date_to date
);
create index if not exists application_subjects_application_id_idx on application_subjects(application_id);

-- ----------------------------------------------------------------------------
-- settings — a single row of institute-wide configuration
-- ----------------------------------------------------------------------------
create table if not exists settings (
  id int primary key default 1,
  institute_name text,
  public_base_url text,
  exam_centre text,
  signatory_title text,
  signatory_image_url text,
  signature_missing_message text,
  instructions text,
  bank_account_no text,
  bank_micr text,
  bank_ifsc text,
  bank_branch text,
  bank_upi_id text,
  logo_data_url text,
  payment_qr_image_url text,
  student_login_enabled boolean not null default true,
  admin_password text not null default 'admin123',
  registration_opens_at text,
  registration_closes_at text,
  constraint settings_single_row check (id = 1)
);
insert into settings (id) values (1) on conflict (id) do nothing;

-- ----------------------------------------------------------------------------
-- hall ticket number sequence — fallback only (students normally enter their
-- own Roll No.; this is only used if one somehow needs to be auto-assigned)
-- ----------------------------------------------------------------------------
create table if not exists hallticket_sequences (
  course_code text primary key,
  next_value integer not null default 1
);

-- ----------------------------------------------------------------------------
-- student_master — the admin-uploaded list of students eligible for the
-- current examination cycle (one CSV replaces this whole table each time).
-- Used to verify a student before they can access the registration form,
-- either by Roll No. + date of birth, or by mobile number (+ OTP, once a
-- real SMS provider is connected — see the app's Settings for details).
-- ----------------------------------------------------------------------------
create table if not exists student_master (
  roll_no text,
  mobile text,
  dob text,
  name text
);

-- ============================================================================
-- Row Level Security
-- ============================================================================
alter table courses enable row level security;
alter table subjects enable row level security;
alter table applications enable row level security;
alter table application_subjects enable row level security;
alter table settings enable row level security;
alter table hallticket_sequences enable row level security;
alter table student_master enable row level security;

-- ----------------------------------------------------------------------------
-- IMPORTANT — read this before going live with real students
-- ----------------------------------------------------------------------------
-- The pilot policies below allow anyone with your website's address to read
-- and write these tables using the public ("anon") key that ships inside
-- the app's JavaScript. That's fine for a small, closed pilot with people
-- you trust — it's what gets you running today with no extra setup.
--
-- It is NOT appropriate for a real, public examination cycle: anyone with
-- basic browser skills could view or edit other students' personal details,
-- photos, and payment references, or tamper with course/fee data. Before
-- opening registration to real students at scale, replace these with real
-- per-role policies (students can only insert their own application and
-- read their own status by roll no./mobile; only signed-in administrators
-- can read everything or make changes) — this is exactly what the
-- "Database Schema, API Design & Security Requirements" document describes,
-- and your IT/NIC team can implement it directly on these same tables.
--
-- Note in particular: student_master holds every student's mobile number and
-- date of birth — with these pilot policies, that list is just as exposed as
-- everything else here. Treat it with the same caution.
-- ----------------------------------------------------------------------------
drop policy if exists "pilot_all_courses" on courses;
drop policy if exists "pilot_all_subjects" on subjects;
drop policy if exists "pilot_all_applications" on applications;
drop policy if exists "pilot_all_application_subjects" on application_subjects;
drop policy if exists "pilot_all_settings" on settings;
drop policy if exists "pilot_all_hallticket_sequences" on hallticket_sequences;
drop policy if exists "pilot_all_student_master" on student_master;

create policy "pilot_all_courses" on courses for all using (true) with check (true);
create policy "pilot_all_subjects" on subjects for all using (true) with check (true);
create policy "pilot_all_applications" on applications for all using (true) with check (true);
create policy "pilot_all_application_subjects" on application_subjects for all using (true) with check (true);
create policy "pilot_all_settings" on settings for all using (true) with check (true);
create policy "pilot_all_hallticket_sequences" on hallticket_sequences for all using (true) with check (true);
create policy "pilot_all_student_master" on student_master for all using (true) with check (true);
